### ISSUE TITLE
[Bug]: Error when attempting '/polymorph conflicts' command

### ISSUE THREAD

**Issue by SolaceNL** [TheIllusiveC4/Polymorph#244]
### Minecraft Version

1.20.1

### What happened?

The recipe conflict button isn't show up in-game so when attempting to use the command for troubleshooting, the following error occurs.

### How do you trigger this bug?

1. Run command /polymorph conflicts
2.
3.
...

### Loader

Forge

### Loader Version

Forge - 47.2.1

### Mod Version

polymorph-forge-0.49.1+1.20.1

### Relevant Log Outputs

https://pastebin.com/GWuzJTms

**Comment by drakray** [comment]
Also got this with neoforge 47.1.79

<details><summary>Snipet</summary>

```
[14Nov.2023 22:33:44.601] [ForkJoinPool.commonPool-worker-6/INFO] [net.minecraft.server.MinecraftServer/]: [drakray: Searching for recipe conflicts...]
[14Nov.2023 22:33:44.602] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Searching for recipe conflicts...
[14Nov.2023 22:33:44.608] [ForkJoinPool.commonPool-worker-6/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent com/illusivesoulworks/polymorph/server/PolymorphCommands$RecipeWrapper for class com/illusivesoulworks/polymorph/server/PolymorphCommands$CraftingRecipeWrapper in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@6f496d9f on thread Thread[ForkJoinPool.commonPool-worker-6,10,main]
[14Nov.2023 22:33:44.608] [ForkJoinPool.commonPool-worker-6/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: com.illusivesoulworks.polymorph.server.PolymorphCommands$RecipeWrapper
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar:6.0.5+6.0.5+master.eb8e549b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.illusivesoulworks.polymorph.server.PolymorphCommands.lambda$findConflicts$4(PolymorphCommands.java:75) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
</details>

**Comment by DarkPhoenixCoding** [comment]
Fabric - 0.14.24 also having the exact same issue. I'm going to try downgrading and see if that fixes anything.

**Comment by TheIllusiveC4** [comment]
I wasn't able to fully reproduce this, but I did notice some other errors in the command that prevented it from functioning properly. Hopefully the fixes I made in the latest update has resolved this, but please make a new issue if this is still a problem.
