### ISSUE TITLE
Game crashes because of "Fabric Containers (v0)" after installing mod.

### ISSUE THREAD

**Issue by AlNexus** [TheIllusiveC4/Polymorph#46]
Not Enough Crashes says it's Fabric Containers, I don't know why. Minecraft doesn't start after installing this mod, giving this crash.
Here's the log

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2020-12-20 23:34:15 BRT
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-containers-v0'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.6)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zbk000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy50.onInitializeClient(Unknown Source)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122)
    ... 21 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/networking/PacketTypes
    at net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl.init(ScreenProviderRegistryImpl.java:71)
    ... 26 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.PacketTypes
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2477971432 bytes (2363 MB) / 3818389504 bytes (3641 MB) up to 7635730432 bytes (7282 MB)
  CPUs: 4
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
  Suspected Mods: Fabric Loader (fabricloader), Fabric Containers (v0) (fabric-containers-v0)
  Fabric Mods: adapaxels: AdaPaxels 1.0.5+1.16.4
               advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
               allstackable: All Stackable 1.2.7
               allure: Allure 1.2.8
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.1.0-1.16.4
               antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
               anvil_fix: AnvilFix 1.1.3+build.7-1.16
               appleskin: AppleSkin 1.0.11
               architectury: Architectury 1.1.55
               artifice: Artifice 0.13.2+1.16.3
               astromine: Astromine 1.11.4+fabric-1.16.3
               astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
               astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
               astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
               astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
               astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
               autoconfig1u: Auto Config v1 Updated 3.3.1
               backslot: BackSlot 1.1.8
               betternether: Better Nether 5.0.4
               blade: Blade 2.0.0
               blockus: Blockus 2.0.0+1.16.4
               blue_endless_jankson: jankson 1.2.0
               bunch-o-trinkets: Bunch O' Trinkets 1.0.1
               cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
               campanion: Campanion 1.3.1+build.51
               cardinal-components: Cardinal Components API 2.7.4
               cardinal-components-base: Cardinal Components API (base) 2.7.9
               cardinal-components-block: Cardinal Components API (blocks) 2.7.9
               cardinal-components-chunk: Cardinal Components API (chunks) 2.7.4
               cardinal-components-entity: Cardinal Components API (entities) 2.7.4
               cardinal-components-item: Cardinal Components API (items) 2.7.4
               cardinal-components-level: Cardinal Components API (world saves) 2.7.4
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.4
               cardinal-components-util: Cardinal Components API (utilities) 2.7.4
               cardinal-components-world: Cardinal Components API (worlds) 2.7.4
               cavebiomes: Cave Biomes 0.5.1
               chainmail: Chainmail 0.5.0
               cinderscapes: Cinderscapes 1.3.0+build.51
               cleancut: CleanCut mc1.16-2.1-fabric
               clickthrough: ClickThrough 1.16.4-fabric0.25.1-0.3
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               couplings: Couplings 1.3.3
               crawl: Crawl 0.8.1
               crimsonmoon: Crimson Moon 1.2.3-1.16.2
               crowdin-translate: CrowdinTranslate 1.2
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               darkness: True Darkness 1.6.50
               diggusmaximus: Diggus Maximus 1.4.2-1.16.3
               disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               eldritch_mobs: Eldritch Mobs 1.5.4
               elytra_bounce: Elytra Hopping 0.1.0+1.16.1
               enderitemod: Enderite Mod 1.2.2
               expandedstorage: ExpandedStorage 5.6.31
               expcontainer: Experience Container 1.9
               fabric: Fabric API 0.25.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
               fabricloader: Fabric Loader 0.10.6+build.214
               fabriczero: Fabric Zero 0.1.4
               factory: Factory 1.16.2-1.3.0
               fatxporbs: Fat Experience Orbs 0.0.9
               fermion: Fermion 2.1.191
               fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
               fiber: fiber 0.23.0-2
               firstperson: FirstpersonModel 1.3.0
               gbfabrictools: GBfabrictools 1.3.1+1.16.4
               glassdoor: Glass Doors 1.5.0-1.16
               glowsquid: Glowsquid 1.1
               hard-hat-steve: Hard Hat Steve 1.1.1
               harvest: Harvest 1.2.12
               hplus: Hopper Plus 1.0.10
               improved-stations: Improved Stations 2.0.3
               infinitemusic: Infinite Music 1.3.0
               inventoryprofiles: Inventory Profiles 0.4.2
               jankson: Jankson 3.0.1+j1.2.0
               jargm: Just Another Redstone Gate Mod 1.2.0
               kirin: Kirin UI 1.7-1.16.2
               kyrptconfig: Kytpt Config 1.1.4-1.16
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               launchersmod: Launchers 2.2.0
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.0.0+1.16.3
               libstructure: LibStructure 1.5
               linkedstorage: Linked Storage 1.3.11-1.16
               litematica: Litematica 0.0.0-dev.20201103.184101
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.3-1.16.2
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               mambience: MAmbience 2.1.0+1.16.2
               materialisation: Materialisation 3.0.3
               maybe-data: Maybe data 1.0.0-1.16.2
               mcda: MC Dungeons Armors 0.7.6
               mcdw: MC Dungeons Weapons 2.2.2
               minecraft: Minecraft 1.16.4
               minihud: MiniHUD 0.19.0-dev.20201103.184029
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.13+build.19
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               mousewheelie: Mouse Wheelie 1.5.10+mc1.16.4
               netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.9.25
               patchouli: Patchouli 1.16.2-44-FABRIC
               phonos: Phonos 0.1.0-beta
               phosphor: Phosphor 0.7.0+build.10
               piglib: Piglib 1.0.1
               plantinajar: Plant In A Jar 1.8.1
               platos: Plato's Transporters 1.6.2
               polymorph: Polymorph 0.0.6-1.16.4
               presencefootsteps: Presence Footsteps r28+1.16.2
               raisedclouds: Raised Clouds 1.0.0
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.5.0+build.84
               repurposed_structures: Repurposed Structures 1.16.4-1.7.3
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               satin: Satin 1.4.1
               shapes: Shapes 2.0.0+build.10
               simpledrawers: Simple Drawers 1.8.0-1.16.3
               simplevoidworld: Simple Void World 4.0.0
               simplexterrain: Simplex Terrain 0.7.1
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               splash: Splash 1.1.1
               spruceui: SpruceUI 1.6.4
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.6.1+build.143
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               torcherino: Torcherino 2.12.69
               torohealth: ToroHealth Damage Indicators 1.16.4-fabric-3
               traverse: Traverse 3.0.3+build.13
               trinkets: Trinkets 2.6.7
               tweakeroo: Tweakeroo 0.10.0-dev.20201110.132827
               tweed: Tweed API 3.0.0-beta.20
               vanilla-toolsets: Vanilla Toolsets 1.3.0
               voxelmap: VoxelMap 1.10.14
               voyager: Voyager 1.0.0
               waila: Hwyla 1.9.22
               waystones: Waystones 1.0.9
               whereisit: Where Is It 1.9.1
               wrenchable: Wrenchable 1.0.0+1.16.1
               zoob: Monster Of The Ocean Depths 2.5.0
  Patchouli open book context: n/a
  Launched Version: 1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown> (My CPU is an i3-3220, idk if this helps)

**Comment by AlNexus** [comment]
Works after updating Fabric API! Awesome mod btw.
