### ISSUE TITLE
Crashes, when I use mod "Go fish"

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/Polymorph#81]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/21/21 10:08 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'go-fish'!
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.client.MinecraftClient.redirect$znm000$catchFabricInit(MinecraftClient:6377)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at dev.onyxstudios.cca.internal.block.CardinalBlockInternals.lambda$createComponents$0(CardinalBlockInternals.java:62)
	at java.util.HashMap.computeIfAbsent(Unknown Source)
	at dev.onyxstudios.cca.internal.block.CardinalBlockInternals.createComponents(CardinalBlockInternals.java:47)
	at net.minecraft.block.entity.BlockEntity.handler$zim000$init(BlockEntity:1572)
	at net.minecraft.block.entity.BlockEntity.<init>(BlockEntity:34)
	at draylar.gofish.entity.block.AstralCrateBlockEntity.<init>(AstralCrateBlockEntity.java:10)
	at draylar.gofish.client.item.AstralCrateItemRenderer.<init>(AstralCrateItemRenderer.java:18)
	at draylar.gofish.GoFishClient.onInitializeClient(GoFishClient.java:27)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 20 more
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56)
	... 29 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Unknown Source)
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:31)
	at net.minecraft.class_310.redirect$znm000$catchFabricInit(class_310.java:6379)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 402610512 bytes (383 MB) / 1196949504 bytes (1141 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx2048m
	Suspected Mods: Cardinal Components API (blocks) (cardinal-components-block), Fabric Loader (fabricloader), Go Fish (go-fish)
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.17.22
		artifice: Artifice 0.14.6+1.16.5
		artisanat: Artisanat 2.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks 2.0.1+1.16.5
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blur: Blur (Fabric) 2.1.0
		bundlesplus: bundles plus 0.1.8
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		chat_heads: Chat Heads 0.2.2+1.16.2
		cherishedworlds: Cherished Worlds 1.3.0-1.16.4
		chickendropfeathers: Chicken Drop Feathers 1.0
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		couplings: Couplings 1.3.3
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.3
		darkness: True Darkness 1.6.58
		dawn: Dawn API 1.8
		desolation: Desolation 1.1.1
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		enhanced_mushrooms: Enhanced Mushrooms 1.0.4
		entityculling: EntityCulling-Fabric 1.2.2
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.6
		ferritecore: FerriteCore 2.0.4
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.39
		go-fish: Go Fish 1.2.1-beta-1.16.4
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harvest: Harvest 1.2.12
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libstructure: Libstructure 1.3
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.5
		modmenu: Mod Menu 1.16.9
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		namepain: Name Pain 1.3.1
		norecipebook: NoRecipeBook 2.1+1.16.5
		notenoughcrashes: Not Enough Crashes 3.2.0
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		phosphor: Phosphor 0.7.2+build.12
		polymorph: Polymorph 0.0.10-1.16.5
		rare-ice: Rare Ice 0.2.2
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		satin: Satin 1.5.1
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		sodium: Sodium 0.1.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		survivalisland: Survival Island 0.1.5
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		traverse: Traverse 3.3.2
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		wthit: wthit 2.10.5
		yungsapi: YUNG's API 1.16.5-Fabric-5
		zoob: Monster Of The Ocean Depths 3.0.0
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by TheIllusiveC4** [comment]
I'm not sure what was causing this issue, perhaps just due to outdated CCA or a mismatch somewhere, but this should be fixed in 0.0.11-1.16.5. Please try out the latest version and let me know if the issue persists.
