### ISSUE TITLE
Running /polymorph conflicts does nothing but create error in console

### ISSUE THREAD

**Issue by itsdinkd** [TheIllusiveC4/Polymorph#97]
1.17.1
Latest version of polymorph
Fabric

to reproduce: 
1. Type /polymorph conflicts
2. Check console

Modpack: Another Quality Modpack 2

[00:39:56] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot read the array length because "<local11>" is null
[00:39:56] [Server thread/INFO]: [STDERR]: 	at top.theillusivec4.polymorph.server.PolymorphCommands.lambda$findConflicts$4(PolymorphCommands.java:95)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at top.theillusivec4.polymorph.server.PolymorphCommands.lambda$findConflicts$5(PolymorphCommands.java:68)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at top.theillusivec4.polymorph.server.PolymorphCommands.findConflicts(PolymorphCommands.java:62)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at top.theillusivec4.polymorph.server.PolymorphCommands.lambda$register$2(PolymorphCommands.java:45)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.redirect$zbb000$performCommand(class_2170.java:547)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:251)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_14370(class_3244.java:1222)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_31286(class_3244.java:1206)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_12048(class_3244.java:1189)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2797.method_12115(class_2797.java:30)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2797.method_11054(class_2797.java:7)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2600.method_11072(class_2600.java:21)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.redirect$ghn000$redirectExecuteTask(class_1255.java:521)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$dba000$modifiedRunLoop(MinecraftServer.java:8399)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[00:39:56] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by TheIllusiveC4** [comment]
I rewrote the whole command in Polymorph 0.15-1.17.1+ so this issue should be resolved. If not, it's likely of a different nature and you should open up a new issue with the new error logs if that occurs.
